version: '3.0'

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_nodejs
  bot:
    build:
      dockerfile: Dockerfile
      context: "./apps/bot/"
    restart: always
    environment:
      - RABBITMQ_CONTAINER_NAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=your-password
      - RABBITMQ_DEFAULT_PORT=5672
      - TELEGRAM_BOT_TOKEN=your-bot-token
      - TELEGRAM_BOT_USERNAME=your-bot-username-example-@test123
    volumes:
      - type: bind
        source: ./apps/bot
        target: /app
    depends_on:
      - rps_server
    networks:
        - rabbitmq_nodejs
    ports:
      - 3000:3000

  rps_server:
    build:
      dockerfile: Dockerfile
      context: "./apps/rpsServer/"
    restart: always
    environment:
      - RABBITMQ_CONTAINER_NAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=your-password
      - RABBITMQ_DEFAULT_PORT=5672
      - TELEGRAM_BOT_TOKEN=your-bot-token
      - TELEGRAM_BOT_USERNAME=your-bot-username-example-@test123
    depends_on:
      - rabbitmq
    volumes:
      - type: bind
        source: ./apps/rpsServer
        target: /app
    networks:
        - rabbitmq_nodejs

networks:
  rabbitmq_nodejs:
    driver: bridge