version: '3.0'

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_nodejs
  bot:
    build:
      dockerfile: Dockerfile
      context: "./bot"
    restart: always
    volumes:
      - type: bind
        source: ./apps/bot
        target: /app
    depends_on:
      - rabbitmq
    networks:
        - rabbitmq_nodejs
    ports:
      - 3000:3000

  rps_server:
    build:
      context: "./rpsServer"
    restart: always
    depends_on:
      - rabbitmq
    volumes:
      - type: bind
        source: ./apps/rpsServer
        target: /app
    networks:
        - rabbitmq_nodejs
    
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040

networks:
  rabbitmq_nodejs:
    driver: bridge